### ISSUE TITLE
Trojan.Heur!.02046823

### ISSUE THREAD

**Issue by bart-ctrl** [vsousa14/FiveM-Server-Launcher#4]
<img width="893" alt="image" src="https://user-images.githubusercontent.com/114456007/198572019-8b39e851-ca4b-4547-a111-8ee6961e7e60.png">
https://www.virustotal.com/gui/file/a40a9261950e73960650638733ce05920ee014b957623892889345d924f6be35?nocache=1
ran both the one outside win-unpacked folder, gave 0. one inside win-unpacked folder gave 1.
..let me note before someone says some fuck shit..I don't think this is malicious could honestly be a false flag

**Comment by vsousa14** [comment]
Hey there.
If you build the app and send the installer to someone, it also says that may contain malicious files, that's because the app isn't verified and the OS detects it as a virus, and from what I read, in order to remove those warnings you need to submit the app through a Microsoft program so they can analyze the app and decide if is malicious or not.

**Comment by bart-ctrl** [comment]
> Hey there. If you build the app and send the installer to someone, it also says that may contain malicious files, that's because the app isn't verified and the OS detects it as a virus, and from what I read, in order to remove those warnings you need to submit the app through a Microsoft program so they can analyze the app and decide if is malicious or not.

That is exactly the case here. I built it and sent it to someone and they got scared. I immediately assumed false flag, I have made simpler things then this and have gotten crazy responses from virus total for MY OWN stuff that I KNOW doesn't do any of the things being flagged. I reviewed every file as well I don't see anything alarming at all either. Thank you for such a fast reply and a better explanation!

**Comment by vsousa14** [comment]
No problem, glad it cleared up.
