### ISSUE TITLE
Doesn't find server

### ISSUE THREAD

**Issue by SenkaWolf** [vsousa14/FiveM-Server-Launcher#5]
I've set up the launcher however it can't seem to find my server so it doesn't list anything like players etc. The IP I am using is "xbqoae". 

This is as far as the application gets: https://i.senkawolf.com/04-01-23_19.25.51.png

If I put the IP at the end of the URLs used inside index.js it comes back with data. As seen here: https://servers-frontend.fivem.net/api/servers/single/xbqoae

I've only modified the config file, images, and some CSS.

**Comment by vsousa14** [comment]
Hello, FiveM apparently changed their API, I will be working on a solution soon

**Comment by vsousa14** [comment]
Hello, the launcher is working again without issues, please download last version :)
