### ISSUE TITLE
NOT FIND SERVER

### ISSUE THREAD

**Issue by trollolobrhue** [vsousa14/FiveM-Server-Launcher#6]
The IP I am using is "b88pz8".

This is as far as the application gets: https://ibb.co/jrYBpKs

As seen here: https://servers-frontend.fivem.net/api/servers/single/b88pz8

HELP PLZ

**Comment by DavidCV0100** [comment]
Trying to fix it.

**Comment by vsousa14** [comment]
Hello, FiveM apparently changed their API, I will be working on a solution soon

**Comment by vsousa14** [comment]
Hello, the launcher is already working with server ID's , please download last version
